version: '3.8'

services:
  web:
    image: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mssql
    restart: always
    volumes:
      - portfolio:/var/lib/mssql/data
      - ./database/:/code
    environment:
      MSSQL_DB: 'portfolio'
      MSSQL_USER: 'mssql'
      MSSQL_PASSWORD: '123'
    ports:
      - 5432:5432

volumes:
  portfolio: